import { registerWorkflowCases } from "./fixtures/workflow-cases.ts";

registerWorkflowCases(["opinion-stale-checks","opinion-deadline","opinion-missing", "opinion-readonly", "opinion-unsupported","deadline-verifier","history-model","auto-model", "auto-model-off", "auto-model-repair","opinion-different-reviewer","opinion-off","schedule-restart-future", "schedule-missed","child-usage","scheduled","opinion-unresolved", "opinion-zero", "opinion-revise", "second-opinion",
  "replan-repair",
  "replan-zero",
  "proposal-valid",
  "proposal-stale",
  "proposal-tool",
  "shared-directory",
  "shared-directory-drift",
  "writers-disabled-command",
  "writers-disabled-tool",
  "scope-forged-input",
  "check-threshold-change",
  "premature-critic",
  "budget-local-verification",
  "step-cap",
  "cancel",
  "same-model-repair",
  "critique",
  "critic-reserve",
  "critique-revise",
  "tool-entry",
  "combined-recipes",
  "scope-job-cap",
  "scope-fork-cap",
  "scope-semantic-cap",
  "cancel-verifier-first",
  "cancel-verifier-late"
]);
