"""实例扩展通过受管本地桥调用已核验运行包；不依赖全局 node_modules。"""
import re
from .schema import ConfigError


HELPERS = ("agentStateClient", "checkpointClient", "inspectGitStatus", "assertSessionBoundary", "requireOrdinaryHelper")
MODULES = frozenset(("service-bindings", "checkpoints", "git-status", "capability-policy"))


def extension_source(raw):
  text = raw.decode("utf8")
  def replace(match):
    if match[2] not in MODULES: raise ConfigError("pi-extension-helper-unbound")
    return match[1] + "../agentcfg-runtime-api.mjs" + match[1]
  text = re.sub(r"([\"'])@agentcfg/pi-runtime/([^\"']+)\1", replace, text)
  if "@agentcfg/pi-runtime/" in text: raise ConfigError("pi-extension-helper-unbound")
  return text.encode()


def bridge_source():
  lines = ["// Generated by agentcfg; runtime authority stays with the active instance.",
    'function call(name, args) {',
    '  const runtime = globalThis[Symbol.for("agentcfg.pi.runtime.v1")];',
    '  if (!runtime || args[0] !== runtime || typeof runtime.extensionApi?.[name] !== "function") throw new Error("PI_EXTENSION_RUNTIME_UNAVAILABLE");',
    '  return runtime.extensionApi[name](...args);',
    '}']
  lines.extend('export const ' + name + ' = (...args) => call("' + name + '", args);' for name in HELPERS)
  return ("\n".join(lines) + "\n").encode()
